Feature/comment bug
ContainerRestaurant/ContainerRestaurant-Server pull request #105
Opened 2021-06-04 15:23 UTC by HongYeseul

#98 
3. 대댓글이 없는 댓글 삭제 시 ```NullPointerException``` 오류
이 부분은 어떤 내용인지 잘 이해를 못해서... 일단 제외하고 PR 넣어봅니다.
기타 - 1. ```UpperRelies``` 변수 네이밍 컨벤션 수정
1번의 수정 부분은 제가 한 부분이 맞는지 확인 해 주시면 좋을 것 같습니다..! 😂

2021-06-05 04:44 UTC, Cenibee requested changes

2021-06-05 04:44 UTC, Cenibee commented on src/main/java/container/restaurant/server/domain/comment/CommentService.java
> +        Comment upperReplies = ofNullable(commentCreateDto.getUpperReplyId())
이거는 바꾼 이유가 있나요?? 단수가 맞는것같은데....

2021-06-05 04:44 UTC, Cenibee commented on src/main/java/container/restaurant/server/domain/comment/CommentService.java
> +        List<Comment> UpperReplies = commentRepository.findAllByUpperReplyId(upperReply.getId());
기타 1번 UpperRelies 변수 네이밍 컨벤션 수정

오류 3번 대댓글이 없는 댓글 삭제 시 NullPointerException 오류
- comment.getUpperReply() 가 널인 경우

2021-06-05 04:44 UTC, Cenibee commented on src/main/java/container/restaurant/server/web/CommentController.java
> +                        commentLikeLinker.userCancelLikeComment(dto.getId()).withRel("cancel-like")
자 일단 like/cancel-like 모두 해당 댓글 좋아요 여부 없이 들어가있는거는 선택의 문제라서 어떤게 좋을지 고민해봐야할 포인트는 맞는것 같습니다.
그런데 현재 사용자가 각 댓글들을 좋아요 했는지 안했는지 여부를 구분할 수 없을 것 같네요. 이 문제도 같이 해결해야 할 것 같습니다.

2021-06-05 05:28 UTC, HongYeseul commented on src/main/java/container/restaurant/server/web/CommentController.java
> +                        commentLikeLinker.userCancelLikeComment(dto.getId()).withRel("cancel-like")
음.. 그러면 일단 이 상태로 놔두자는 말씀 맞으신가요? 추 후 고민해보자는 그런..

2021-06-05 05:30 UTC, HongYeseul commented on src/main/java/container/restaurant/server/domain/comment/CommentService.java
> +        List<Comment> UpperReplies = commentRepository.findAllByUpperReplyId(upperReply.getId());
아 혹시 UpperReplies 변수 명을 upperReplies로 변경 하라고 하셨던건가요,,,!!!? 😅

2021-06-05 06:45 UTC, Cenibee commented on src/main/java/container/restaurant/server/domain/comment/CommentService.java
> +        List<Comment> UpperReplies = commentRepository.findAllByUpperReplyId(upperReply.getId());
아 넵넵 ㅋㅋㅋㅋ 컨벤션이 안맞길래,,,

2021-06-05 06:46 UTC, Cenibee commented on src/main/java/container/restaurant/server/web/CommentController.java
> +                        commentLikeLinker.userCancelLikeComment(dto.getId()).withRel("cancel-like")
일단 좋아요 상태 알수있도록은 구현 ㄱㄱ
like/cancel-like 둘다 있게할지는 상태 알 수 있을때 다시 고민해봅시다 ㅋㅋㅋ

2021-08-02 01:59 UTC, closed without merging

2021-08-02 01:59 UTC, Cenibee commented
다른 PR 로 수정되어 해당 PR 을 종료합니다.