:sparkles: 식당 대표 이미지 적용 추가
ContainerRestaurant/ContainerRestaurant-Server pull request #132
Opened 2021-08-04 15:08 UTC by Parkjung1129

피드 쓰기 수행 시 식당의 대표 이미지도 함께 적용

기준 : 해당 식당으로 피드 조회 시 좋아요가 많고 이미지 가 있는 피드를 반환해 해당 이미지를 식당 대표이미지로 적용

처음 식당이 등록되는 경우 방금 등록된 피드의 이미지를 대표 이미지로 적용

피드 작성 시 식당 대표이미지 변경
피드 좋아요 시는 현재 적용 X

2021-08-04 15:22 UTC, Parkjung1129 commented
새로 작성된 피드가 save 되고 대표 이미지를 가져오는 순서라 null 체크는 별도로 하지 않았습니다
피드의 이미지는 필수라고 알고 있어서

2021-08-05 03:06 UTC, Cenibee requested changes

2021-08-05 03:06 UTC, Cenibee commented on src/main/java/container/restaurant/server/domain/feed/FeedRepository.java
> +    Feed findFirstByRestaurantIdAndThumbnailIdIsNotNullOrderByLikeCountDesc(Long restaurantId);
메서드 이름이 너무 길어진 것 같은데 JPQL 을 써보는건 어떨까요??

2021-08-05 03:06 UTC, Cenibee commented on src/main/java/container/restaurant/server/domain/feed/FeedService.java
> +        restaurant.setThumbnail(findRestaurantRepFeedThumbnail(restaurant));
위 로직대로면, 모든 피드 쓰기 요청시마다 피드 식당에 작성된 모든 피드의 좋아요 수로 정렬하고 카운트가 가장 높은 피드의 사진을 식당의 사진으로 설정하는거 같은데... 의도하신 동작이 맞을까요??

2021-08-05 03:06 UTC, Cenibee commented on src/main/java/container/restaurant/server/domain/feed/FeedService.java
> +        return repFeed.getThumbnail();
피드의 이미지는 필수가 아닙니다..!

2021-08-05 11:22 UTC, Parkjung1129 commented on src/main/java/container/restaurant/server/domain/feed/FeedRepository.java
> +    Feed findFirstByRestaurantIdAndThumbnailIdIsNotNullOrderByLikeCountDesc(Long restaurantId);
JPQL 에서 LIMIT 를 사용을 못해서 일반 쿼리로 해야될거 같은뎅

2021-08-05 11:23 UTC, Parkjung1129 commented on src/main/java/container/restaurant/server/domain/feed/FeedService.java
> +        restaurant.setThumbnail(findRestaurantRepFeedThumbnail(restaurant));
네 우선 이미지가 필수라고 생각해서 식당이 최초 생성될 때도 대표이미지 가져가게 하려구 그렇게 두었습니당

2021-08-05 11:24 UTC, Parkjung1129 commented on src/main/java/container/restaurant/server/domain/feed/FeedService.java
> +        return repFeed.getThumbnail();
요걸 몰랐넹

2021-08-05 11:42 UTC, Parkjung1129 commented on src/main/java/container/restaurant/server/domain/feed/FeedService.java
> +        return repFeed.getThumbnail();
성중님 현재 피드 쓰기 할 때 이미지 null 일경우 ResourceNotFoundException 발생하는데.. 요 ?

2021-08-05 11:42 UTC, Cenibee commented on src/main/java/container/restaurant/server/domain/feed/FeedRepository.java
> +    Feed findFirstByRestaurantIdAndThumbnailIdIsNotNullOrderByLikeCountDesc(Long restaurantId);
LIMIT 부분 제외하고 JPQL 만들고, Spring Data Jpa 에서 제공하는 Pagealbe 인터페이스를 인수로 받으시면 LIMIT 을 대체할 수 있을것 같아요.
`PagingAndSortingRepository`, `Pageable`, `PageRequest` 클래스/인터페이스 참고하셔서 한 번 구현해볼 수 있을것 같습니다!

2021-08-05 11:49 UTC, Cenibee commented on src/main/java/container/restaurant/server/domain/feed/FeedService.java
> +        return repFeed.getThumbnail();
에?? 왜죠 ㅋㅋㅋㅋㅋ

2021-08-05 12:31 UTC, Parkjung1129 commented on src/main/java/container/restaurant/server/domain/feed/FeedRepository.java
> +    Feed findFirstByRestaurantIdAndThumbnailIdIsNotNullOrderByLikeCountDesc(Long restaurantId);
List 로 받아서 0번 째 뽑는 것보다 효율이 있을까요 ?? 이건 잘몰라서 안쓰구 있었는뎅 ㅋㅋㅋㅋ 한번 봐보겠습니다

2021-08-06 13:01 UTC, Cenibee commented on src/main/java/container/restaurant/server/domain/feed/FeedService.java
> +        return repFeed.getThumbnail();
해당 내용 수정완료

2022-01-09 13:08 UTC, closed without merging