Feature/delete comment
ContainerRestaurant/ContainerRestaurant-Server pull request #66
Opened 2021-05-21 07:08 UTC by HongYeseul

댓글 삭제 기능을 수정한 PR 입니다.
현재 댓글 확인을 로그인 했을 때만 가능한 것 같은데, 추후 수정해야할 것 같습니다.

2021-05-21 13:10 UTC, Parkjung1129 approved these changes

2021-05-21 15:22 UTC, Cenibee requested changes
일하시지요 ㅋㅋㅋ

2021-05-21 15:22 UTC, Cenibee commented on src/main/java/container/restaurant/server/domain/comment/CommentService.java
> +            comment.setIsDeleted();
여기 아래 return 넣으면 아래 else 구문 생략할 수 있어요

2021-05-21 15:22 UTC, Cenibee commented on src/main/java/container/restaurant/server/web/dto/comment/CommentInfoDto.java
> +        this.isDeleted = false;
from() 함수에 있는 조건문 여기로 가져와서 좀 더 단순화 시킬수 있을것 같아요

2021-05-22 02:11 UTC, HongYeseul commented on src/main/java/container/restaurant/server/web/dto/comment/CommentInfoDto.java
> +        this.isDeleted = false;
이 방법이.. 어떤건지 감이 잘 안와옵니다 ㅠㅠ

2021-05-22 08:13 UTC, Cenibee commented on src/main/java/container/restaurant/server/web/dto/comment/CommentInfoDto.java
> +        this.isDeleted = false;
에구궁 속성이 다 final 이라서 생각보다 간결해지진 않겠군요 ㅋㅋㅋ 그냥 해결된거로 해둘게용

2021-05-22 08:13 UTC, Cenibee approved these changes

2021-05-22 10:34 UTC, HongYeseul commented on src/main/java/container/restaurant/server/web/dto/comment/CommentInfoDto.java
> +        this.isDeleted = false;
앟ㅎ...ㅎㅎ 감사합니다 머지할게요!!!

2021-05-22 10:34 UTC, merged