Feature/banner
ContainerRestaurant/ContainerRestaurant-Server pull request #87
Opened 2021-05-28 06:13 UTC by HongYeseul

2021-05-28 10:36 UTC, Cenibee requested changes

2021-05-28 10:36 UTC, Cenibee commented on src/main/java/container/restaurant/server/web/linker/BannerLinker.java
> +public class BannerLinker {
IndexController 를 이용해서 만드니 안헷갈리게 IndexLinker 로 하는게 좋을 것 같아요

2021-05-28 10:36 UTC, Cenibee commented on src/main/java/container/restaurant/server/web/dto/IndexDto.java
> +import java.util.List;
임포트 안쓰는거 제거해주세요

2021-05-28 10:36 UTC, Cenibee commented on src/main/java/container/restaurant/server/domain/banner/BannerService.java
> +    }
1. 여기도 자주 변경되지 않는 쿼리가 반복적으로 발생하니까 StatisticsService 처럼 메모리에 banners 를 한번 저장해두고 주기적으로 업데이트 해보는건 어떨까요?
2. baseURL 을 Linker 안쓰고 ImageController 에 있는 DEFAULT_PATH 를 public static 으로 변경해서 쓰는게 좋을 것같은데... 이건 @Parkjung1129 님도 그렇게 써도 좋을지 확인 한 번 부탁드려요

2021-05-29 10:09 UTC, HongYeseul commented on src/main/java/container/restaurant/server/domain/banner/BannerService.java
> +    }
@Parkjung1129

2021-05-29 10:09 UTC, HongYeseul commented on src/main/java/container/restaurant/server/domain/banner/BannerService.java
> +    }
확인이 늦었습니다.. ㅠ 내일 안으로 다시 커밋 넣을 수 있도록 하겠습니다

2021-05-29 11:44 UTC, Parkjung1129 commented on src/main/java/container/restaurant/server/domain/banner/BannerService.java
> +    }
아뇨 그 DEFAULT_PATH 는 이미지 파일 서버에 기본 경로를 지정한거라 지금 링커 형태가 나을것 같습니다 ~
클라이언트에서 파일서버 주소를 모르게 하기 위해서 ImageController 의 getImage 를 타게끔 하려구 링커를 사용 해써용

2021-05-29 11:44 UTC, Parkjung1129 approved these changes

2021-05-30 02:18 UTC, HongYeseul commented on src/main/java/container/restaurant/server/domain/banner/BannerService.java
> +    }
말씀하신 내용 중 baseURL 관련 빼고는 커밋 넣었습니다!

2021-05-30 03:02 UTC, Cenibee commented on src/main/java/container/restaurant/server/domain/banner/BannerService.java
> +    }
확인했습니다

2021-05-30 03:02 UTC, Cenibee approved these changes

2021-05-30 11:54 UTC, merged