피드쓰기 시 식당 저장 로직 추가
ContainerRestaurant/ContainerRestaurant-Server pull request #96
Opened 2021-05-31 13:08 UTC by Parkjung1129

2021-06-01 05:57 UTC, Cenibee requested changes
DTO 에서는 이미지 ID 말고 URL 로 전달 하는게 좋을 것 같습니다.(links로 보내기엔 확장성이 결함이 생길것 같아요)
RestaurantDto 클래스를 만들어서 식당이 생성될 때 정보를 처리하는 책임을 클래스를 별도로 분리하는게 좋을것 같습니다.

2021-06-01 05:57 UTC, Cenibee commented on src/main/java/container/restaurant/server/domain/restaurant/RestaurantService.java
> +    }
`RestaurantDto` 클래스를 따로 지정하고, `RestaurantService.save()` 대신 `RestaurantService.findByDto()` 라는 함수 이름을 사용하는건 어떨까요? (저장하는 작업만 하는게 아니니까요!)

그리고 어차피 같은 도메인이고 추가처리 없으니 `findByName`은 따로 함수로 뺴지 않아도 될 것 가타용

대략적으로 그림으로 나타내 봤습니다
![image](https://user-images.githubusercontent.com/30590761/120272415-08c10200-c2e8-11eb-8b60-1a8b902206cb.png)
![image](https://user-images.githubusercontent.com/30590761/120272431-0d85b600-c2e8-11eb-8b42-41cf44a3e53a.png)

2021-06-01 05:57 UTC, Cenibee commented on src/main/java/container/restaurant/server/domain/feed/FeedService.java
> +        Restaurant restaurant = restaurantService.save(dto.getRestaurant());
`findByDto()` 로 대체될 수 있음

2021-06-01 05:57 UTC, Cenibee commented on src/main/java/container/restaurant/server/domain/feed/FeedService.java
> +        Restaurant restaurant = restaurantService.findById(dto.getRestaurant().getId());
`findByDto()` 로 대체될 수 있음

2021-06-01 05:57 UTC, Cenibee commented on src/main/java/container/restaurant/server/web/dto/feed/FeedPreviewDto.java
> +    private final Long thumbnailImageId;
응답 DTO 에서는 URL 로 주는게 나을 것 같은데.... 이렇게 ID 로 주면 실제 이미지를 가져오는 링크를 _links 로 제공해줘야할 것 같은데, 그렇게 되면 여러 이미지를 내려줄때 생각해야할 사항이 많아질것 같아요 FeedService에서 dto 만들 때 이미지 url 까지 만들어서 dto에 넣어주는게 좋을 것같아요

2021-06-01 05:57 UTC, Cenibee commented on src/main/java/container/restaurant/server/web/dto/feed/FeedInfoDto.java
> +    private final Long thumbnailImageId;
응답 DTO 에서는 URL 로 주는게 나을 것 같은데.... 이렇게 ID 로 주면 실제 이미지를 가져오는 링크를 _links 로 제공해줘야할 것 같은데, 그렇게 되면 여러 이미지를 내려줄때 생각해야할 사항이 많아질것 같아요 FeedService에서 dto 만들 때 이미지 url 까지 만들어서 dto에 넣어주는게 좋을 것같아요 (중복)

2021-06-01 08:49 UTC, Cenibee commented
+ 혹시 이거 documentaion 으로 되어있는데 잘못 설정하신것 같아용 ㅋㅋㅋㅋ

2021-06-02 04:31 UTC, Cenibee approved these changes
RestaurantCreateDto ID 안쓸것 같은데 안쓰면 추가로 삭제해주세요!

2021-06-02 04:31 UTC, Cenibee commented on src/main/java/container/restaurant/server/web/dto/restaurant/RestaurantCreateDto.java
> +    private final Long id;
요거 안쓰면 지워도 될것 같아요

2021-06-02 04:35 UTC, Parkjung1129 commented on src/main/java/container/restaurant/server/web/dto/restaurant/RestaurantCreateDto.java
> +    private final Long id;
요거 updateRelationalAttrs 요기서 식당 findById 사용해서 추가해 두었습니당

2021-06-02 04:42 UTC, Cenibee commented on src/main/java/container/restaurant/server/web/dto/restaurant/RestaurantCreateDto.java
> +    private final Long id;
아아 업데이트에서 사용할 수도있군영 그럼 RestaurantCreateDto가 수정에도 사용하니 Info나 다른 네이밍 사용하는건 어떨까용??

2021-06-02 07:43 UTC, Cenibee commented on src/main/java/container/restaurant/server/web/dto/restaurant/RestaurantCreateDto.java
> +    private final Long id;
https://velog.io/@p4rksh/Spring-Boot%EC%97%90%EC%84%9C-%EA%B9%94%EB%81%94%ED%95%98%EA%B2%8C-DTO-%EA%B4%80%EB%A6%AC%ED%95%98%EA%B8%B0
추후적용해보기

2021-06-02 12:58 UTC, HongYeseul approved these changes
와웅,,, 수고 많으셨네요ㅠㅠ 감사합니다..!!!

2021-06-02 13:49 UTC, merged